#!/bin/bash



# Directory for the backups

BACKUP_DIR=~/secure_backups

OLD_BACKUP_DIR="$BACKUP_DIR/old"

TMP_DIR="$BACKUP_DIR/tmp"



# Assuming you have a differences file generated by the evening script

DIFF_FILE=$(ls "$BACKUP_DIR/differences_"* | sort -n | tail -1)



# Extract only the paths of changed files

CHANGED_FILES=$(awk '{print $NF}' "$DIFF_FILE" | grep "^/etc" | sed 's/^\///')



# Create a temporary directory for extracting changed files from backup

mkdir -p "$TMP_DIR"



# Extracting the files from the compressed backup

BACKUP_FILE=$(ls "$OLD_BACKUP_DIR/etc_backup_"* | sort -n | tail -1)

for file in $CHANGED_FILES; do

    sudo tar -xf "$BACKUP_FILE" "$file" -C "$TMP_DIR"

done



# Now compare each file with its counterpart in /etc

for file in $CHANGED_FILES; do

    # Ensure both files exist before diffing

    if [ -f "$file" ] && [ -f "$TMP_DIR/$file" ]; then

        DIFF_CONTENT=$(diff "$TMP_DIR/$file" "$file")

        if [ ! -z "$DIFF_CONTENT" ]; then

            echo "Differences in $file:" > "$BACKUP_DIR/detailed_diff_$(basename $file)_$(date +%F_%H-%M-%S).txt"

            echo "$DIFF_CONTENT" >> "$BACKUP_DIR/detailed_diff_$(basename $file)_$(date +%F_%H-%M-%S).txt"

        fi

    fi

done



# Cleanup temporary directory

rm -rf "$TMP_DIR"

